DROP TABLE IF EXISTS `dbc_map`;
CREATE TABLE `dbc_map` (
	`field0` INT NOT NULL DEFAULT '0',
	`field1` INT NOT NULL DEFAULT '0',
	`field2` INT NOT NULL DEFAULT '0',
	`field3` INT NOT NULL DEFAULT '0',
	`field4` INT NOT NULL DEFAULT '0',
	`field5` INT NOT NULL DEFAULT '0',
	`field6` INT NOT NULL DEFAULT '0',
	`field7` INT NOT NULL DEFAULT '0',
	`field8` INT NOT NULL DEFAULT '0',
	`field9` INT NOT NULL DEFAULT '0',
	`field10` INT NOT NULL DEFAULT '0',
	`field11` INT NOT NULL DEFAULT '0',
	`field12` INT NOT NULL DEFAULT '0',
	`field13` INT NOT NULL DEFAULT '0',
	`field14` INT NOT NULL DEFAULT '0',
	`field15` INT NOT NULL DEFAULT '0',
	`field16` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`field0`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Export of map.db2';

