CREATE TABLE IF NOT EXISTS `creaturecache` (
  `entry` int(10) unsigned NOT NULL DEFAULT '0',
  `name` text NOT NULL,
  `Name2` text NOT NULL,
  `Name3` text NOT NULL,
  `Name4` text NOT NULL,
  `unk1` int(11) NOT NULL DEFAULT '0',
  `subname` text NOT NULL,
  `IconName` text NOT NULL,
  `type_flags` int(10) unsigned NOT NULL DEFAULT '0',
  `type` int(10) unsigned NOT NULL DEFAULT '0',
  `family` int(10) unsigned NOT NULL DEFAULT '0',
  `rank` int(10) unsigned NOT NULL DEFAULT '0',
  `unk2` int(11) NOT NULL DEFAULT '0',
  `KillCredit1` int(11) NOT NULL DEFAULT '0',
  `KillCredit2` int(11) NOT NULL DEFAULT '0',
  `modelid1` int(10) unsigned NOT NULL DEFAULT '0',
  `modelid2` int(10) unsigned NOT NULL DEFAULT '0',
  `modelid3` int(10) unsigned NOT NULL DEFAULT '0',
  `modelid4` int(10) unsigned NOT NULL DEFAULT '0',
  `Health_mod` float NOT NULL DEFAULT '0',
  `Mana_mod` float NOT NULL DEFAULT '0',
  `RacialLeader` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `questItem1` int(10) unsigned NOT NULL DEFAULT '0',
  `questItem2` int(10) unsigned NOT NULL DEFAULT '0',
  `questItem3` int(10) unsigned NOT NULL DEFAULT '0',
  `questItem4` int(10) unsigned NOT NULL DEFAULT '0',
  `questItem5` int(10) unsigned NOT NULL DEFAULT '0',
  `questItem6` int(10) unsigned NOT NULL DEFAULT '0',
  `movementId` int(10) unsigned NOT NULL DEFAULT '0',
  `exp` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;