CREATE TABLE IF NOT EXISTS `gameobjectcache` (
  `entry` mediumint(8) unsigned NOT NULL default '0',
  `type` mediumint(8) unsigned NOT NULL default '0',
  `displayId` mediumint(8) unsigned NOT NULL default '0',
  `name` varchar(255) NOT NULL,
  `name2` varchar(255) NOT NULL,
  `name3` varchar(255) NOT NULL,
  `name4` varchar(255) NOT NULL,
  `iconName` varchar(255) NOT NULL,
  `castBarCaption` varchar(255) NOT NULL,
  `unk1` varchar(255) NOT NULL,
  `data0` mediumint(8) unsigned NOT NULL default '0',
  `data1` mediumint(8) unsigned NOT NULL default '0',
  `data2` mediumint(8) unsigned NOT NULL default '0',
  `data3` mediumint(8) unsigned NOT NULL default '0',
  `data4` mediumint(8) unsigned NOT NULL default '0',
  `data5` mediumint(8) unsigned NOT NULL default '0',
  `data6` mediumint(8) unsigned NOT NULL default '0',
  `data7` mediumint(8) unsigned NOT NULL default '0',
  `data8` mediumint(8) unsigned NOT NULL default '0',
  `data9` mediumint(8) unsigned NOT NULL default '0',
  `data10` mediumint(8) unsigned NOT NULL default '0',
  `data11` mediumint(8) unsigned NOT NULL default '0',
  `data12` mediumint(8) unsigned NOT NULL default '0',
  `data13` mediumint(8) unsigned NOT NULL default '0',
  `data14` mediumint(8) unsigned NOT NULL default '0',
  `data15` mediumint(8) unsigned NOT NULL default '0',
  `data16` mediumint(8) unsigned NOT NULL default '0',
  `data17` mediumint(8) unsigned NOT NULL default '0',
  `data18` mediumint(8) unsigned NOT NULL default '0',
  `data19` mediumint(8) unsigned NOT NULL default '0',
  `data20` mediumint(8) unsigned NOT NULL default '0',
  `data21` mediumint(8) unsigned NOT NULL default '0',
  `data22` mediumint(8) unsigned NOT NULL default '0',
  `data23` mediumint(8) unsigned NOT NULL default '0',
  `data24` mediumint(8) unsigned NOT NULL default '0',
  `data25` mediumint(8) unsigned NOT NULL default '0',
  `data26` mediumint(8) unsigned NOT NULL default '0',
  `data27` mediumint(8) unsigned NOT NULL default '0',
  `data28` mediumint(8) unsigned NOT NULL default '0',
  `data29` mediumint(8) unsigned NOT NULL default '0',
  `data30` mediumint(8) unsigned NOT NULL default '0',
  `data31` mediumint(8) unsigned NOT NULL default '0',
  `size` float NOT NULL default '0',
  `questItem_1` mediumint(8) unsigned NOT NULL default '0',
  `questItem_2` mediumint(8) unsigned NOT NULL default '0',
  `questItem_3` mediumint(8) unsigned NOT NULL default '0',
  `questItem_4` mediumint(8) unsigned NOT NULL default '0',
  `questItem_5` mediumint(8) unsigned NOT NULL default '0',
  `questItem_6` mediumint(8) unsigned NOT NULL default '0',
  `exp` mediumint(8) unsigned NOT NULL default '0',
  PRIMARY KEY  (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;